-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 20:36:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`branch` (
  `BRANCH_ID` INT(11) NOT NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `NAME` VARCHAR(30) NOT NULL,
  `CITY` VARCHAR(30) NULL DEFAULT NULL,
  `STATE` VARCHAR(45) NULL,
  `ZIP_CODE` VARCHAR(12) NULL,
  PRIMARY KEY (`BRANCH_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`customer` (
  `CUST_ID` INT(11) NOT NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` VARCHAR(45) NULL,
  `POSTAL_CODE` VARCHAR(45) NULL,
  `OCUPATION` VARCHAR(45) NULL,
  `CUST_TYPE_CD` VARCHAR(45) NULL,
  PRIMARY KEY (`CUST_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`departament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`departament` (
  `DEPT_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DEPT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`employee` (
  `EMP_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NULL,
  `TITLE` VARCHAR(45) NULL,
  `ASSIGNED_BRANCH_ID` INT(11) NULL,
  `DEPT_ID` INT NULL,
  `SUPERIOR_EMP_ID` INT NULL,
  PRIMARY KEY (`EMP_ID`),
  UNIQUE INDEX `EMP_ID_UNIQUE` (`EMP_ID` ASC) VISIBLE,
  INDEX `fk_employee_branch1_idx` (`ASSIGNED_BRANCH_ID` ASC) VISIBLE,
  INDEX `fk_employee_departament1_idx` (`DEPT_ID` ASC) VISIBLE,
  INDEX `fk_employee_employee1_idx` (`SUPERIOR_EMP_ID` ASC) VISIBLE,
  CONSTRAINT `fk_employee_branch1`
    FOREIGN KEY (`ASSIGNED_BRANCH_ID`)
    REFERENCES `bank`.`branch` (`BRANCH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_departament1`
    FOREIGN KEY (`DEPT_ID`)
    REFERENCES `bank`.`departament` (`DEPT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee1`
    FOREIGN KEY (`SUPERIOR_EMP_ID`)
    REFERENCES `bank`.`employee` (`EMP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`product_type` (
  `PRODUCT_TYPE_CD` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCT_TYPE_CD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`product` (
  `PRODUCT_CD` VARCHAR(20) NOT NULL,
  `DATE_OFFERED` DATE NULL,
  `DATE_RETIRED` DATE NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `product_type_PRODUCT_TYPE_CD` VARCHAR(255) NULL,
  PRIMARY KEY (`PRODUCT_CD`),
  INDEX `fk_product_product_type1_idx` (`product_type_PRODUCT_TYPE_CD` ASC) VISIBLE,
  CONSTRAINT `fk_product_product_type1`
    FOREIGN KEY (`product_type_PRODUCT_TYPE_CD`)
    REFERENCES `bank`.`product_type` (`PRODUCT_TYPE_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`account` (
  `ACCOUNT_ID` INT(11) NOT NULL,
  `AVAIL_BALANCE` FLOAT NULL,
  `PENDING_BALANCE` FLOAT NULL,
  `STATUS` VARCHAR(45) NULL,
  `OPEN_DATE` DATE NOT NULL,
  `LAST_ACTIVITY_DATE` DATE NULL,
  `CLOSE_DATE` DATE NULL,
  `customer_CUST_ID` INT(11) NULL,
  `branch_BRANCH_ID` INT(11) NOT NULL,
  `employee_EMP_ID` INT NOT NULL,
  `product_PRODUCT_CD` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`),
  INDEX `fk_account_branch1_idx` (`branch_BRANCH_ID` ASC) VISIBLE,
  INDEX `fk_account_customer1_idx` (`customer_CUST_ID` ASC) VISIBLE,
  INDEX `fk_account_employee1_idx` (`employee_EMP_ID` ASC) VISIBLE,
  INDEX `fk_account_product1_idx` (`product_PRODUCT_CD` ASC) VISIBLE,
  CONSTRAINT `fk_account_branch1`
    FOREIGN KEY (`branch_BRANCH_ID`)
    REFERENCES `bank`.`branch` (`BRANCH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_customer1`
    FOREIGN KEY (`customer_CUST_ID`)
    REFERENCES `bank`.`customer` (`CUST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_employee1`
    FOREIGN KEY (`employee_EMP_ID`)
    REFERENCES `bank`.`employee` (`EMP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_product1`
    FOREIGN KEY (`product_PRODUCT_CD`)
    REFERENCES `bank`.`product` (`PRODUCT_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`business` (
  `INCORP_DATE` DATE NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `STATE_ID` VARCHAR(45) NULL,
  `customer_CUST_ID` INT(11) NULL,
  PRIMARY KEY (`INCORP_DATE`),
  INDEX `fk_business_customer1_idx` (`customer_CUST_ID` ASC) VISIBLE,
  CONSTRAINT `fk_business_customer1`
    FOREIGN KEY (`customer_CUST_ID`)
    REFERENCES `bank`.`customer` (`CUST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`individual` (
  `BIRTH_DATE` DATE NOT NULL,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `customer_CUST_ID` INT(11) NULL,
  PRIMARY KEY (`BIRTH_DATE`),
  INDEX `fk_individual_customer1_idx` (`customer_CUST_ID` ASC) VISIBLE,
  CONSTRAINT `fk_individual_customer1`
    FOREIGN KEY (`customer_CUST_ID`)
    REFERENCES `bank`.`customer` (`CUST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`officer` (
  `OFFICER_ID` INT(11) NOT NULL,
  `END_DATE` DATE NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `START_DATE` DATE NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `CUST_ID` INT(11) NULL,
  PRIMARY KEY (`OFFICER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`account_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`account_trans` (
  `TXN_ID` BIGINT NOT NULL,
  `AMOUNT` FLOAT NOT NULL,
  `FUNDS_AVAIL_DATE` DATE NOT NULL,
  `TXN_DATE` DATETIME NOT NULL,
  `TXN_TYPE_CD` VARCHAR(45) NULL,
  `ACCOUNT_ID` INT(11) NOT NULL,
  `EXECUTION_BRANCH_ID` INT(11) NOT NULL,
  `TELLER_EMP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`TXN_ID`),
  INDEX `fk_account_trans_account1_idx` (`ACCOUNT_ID` ASC) VISIBLE,
  INDEX `fk_account_trans_branch1_idx` (`EXECUTION_BRANCH_ID` ASC) VISIBLE,
  INDEX `fk_account_trans_employee1_idx` (`TELLER_EMP_ID` ASC) VISIBLE,
  CONSTRAINT `fk_account_trans_account1`
    FOREIGN KEY (`ACCOUNT_ID`)
    REFERENCES `bank`.`account` (`ACCOUNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_trans_branch1`
    FOREIGN KEY (`EXECUTION_BRANCH_ID`)
    REFERENCES `bank`.`branch` (`BRANCH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_trans_employee1`
    FOREIGN KEY (`TELLER_EMP_ID`)
    REFERENCES `bank`.`employee` (`EMP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
